package com.simplebiz.employeeappraisal4;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ID")
   private java.lang.Integer id;
   @org.kie.api.definition.type.Label(value = "Code")
   private java.lang.String code;
   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Position")
   private java.lang.String position;
   @org.kie.api.definition.type.Label(value = "UsageVocationDate")
   private java.lang.Integer usageVocationDate;
   @org.kie.api.definition.type.Label(value = "RemainVocationDate")
   private java.lang.Integer remainVocationDate;
   @org.kie.api.definition.type.Label(value = "ProposedVocationDate")
   private java.lang.Integer proposedVocationDate;
   @org.kie.api.definition.type.Label(value = "ApprovedVocationDate")
   private java.lang.Integer approvedVocationDate;
   @org.kie.api.definition.type.Label(value = "CurrentSalary")
   private java.lang.Double currentSalary;
   @org.kie.api.definition.type.Label(value = "ProposedSalary")
   private java.lang.Double proposedSalary;
   @org.kie.api.definition.type.Label(value = "ApprovedSalary")
   private java.lang.Double approvedSalary;
   @org.kie.api.definition.type.Label(value = "Comment")
   private java.lang.String comment;
   @org.kie.api.definition.type.Label(value = "ApproveComment")
   private java.lang.String approveComment;
   @org.kie.api.definition.type.Label(value = "CurrentVocationDate")
   private java.lang.Integer currentVocationDate;

   public Employee()
   {
   }

   public java.lang.Integer getId()
   {
      return this.id;
   }

   public void setId(java.lang.Integer id)
   {
      this.id = id;
   }

   public java.lang.String getCode()
   {
      return this.code;
   }

   public void setCode(java.lang.String code)
   {
      this.code = code;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getPosition()
   {
      return this.position;
   }

   public void setPosition(java.lang.String position)
   {
      this.position = position;
   }

   public java.lang.Integer getUsageVocationDate()
   {
      return this.usageVocationDate;
   }

   public void setUsageVocationDate(java.lang.Integer usageVocationDate)
   {
      this.usageVocationDate = usageVocationDate;
   }

   public java.lang.Integer getRemainVocationDate()
   {
      return this.remainVocationDate;
   }

   public void setRemainVocationDate(java.lang.Integer remainVocationDate)
   {
      this.remainVocationDate = remainVocationDate;
   }

   public java.lang.Integer getProposedVocationDate()
   {
      return this.proposedVocationDate;
   }

   public void setProposedVocationDate(java.lang.Integer proposedVocationDate)
   {
      this.proposedVocationDate = proposedVocationDate;
   }

   public java.lang.Integer getApprovedVocationDate()
   {
      return this.approvedVocationDate;
   }

   public void setApprovedVocationDate(java.lang.Integer approvedVocationDate)
   {
      this.approvedVocationDate = approvedVocationDate;
   }

   public java.lang.Double getCurrentSalary()
   {
      return this.currentSalary;
   }

   public void setCurrentSalary(java.lang.Double currentSalary)
   {
      this.currentSalary = currentSalary;
   }

   public java.lang.Double getProposedSalary()
   {
      return this.proposedSalary;
   }

   public void setProposedSalary(java.lang.Double proposedSalary)
   {
      this.proposedSalary = proposedSalary;
   }

   public java.lang.Double getApprovedSalary()
   {
      return this.approvedSalary;
   }

   public void setApprovedSalary(java.lang.Double approvedSalary)
   {
      this.approvedSalary = approvedSalary;
   }

   public java.lang.String getComment()
   {
      return this.comment;
   }

   public void setComment(java.lang.String comment)
   {
      this.comment = comment;
   }

   public java.lang.String getApproveComment()
   {
      return this.approveComment;
   }

   public void setApproveComment(java.lang.String approveComment)
   {
      this.approveComment = approveComment;
   }

   public java.lang.Integer getCurrentVocationDate()
   {
      return this.currentVocationDate;
   }

   public void setCurrentVocationDate(java.lang.Integer currentVocationDate)
   {
      this.currentVocationDate = currentVocationDate;
   }

   public Employee(java.lang.Integer id, java.lang.String code,
         java.lang.String name, java.lang.String position,
         java.lang.Integer usageVocationDate,
         java.lang.Integer remainVocationDate,
         java.lang.Integer proposedVocationDate,
         java.lang.Integer approvedVocationDate,
         java.lang.Double currentSalary, java.lang.Double proposedSalary,
         java.lang.Double approvedSalary, java.lang.String comment,
         java.lang.String approveComment,
         java.lang.Integer currentVocationDate)
   {
      this.id = id;
      this.code = code;
      this.name = name;
      this.position = position;
      this.usageVocationDate = usageVocationDate;
      this.remainVocationDate = remainVocationDate;
      this.proposedVocationDate = proposedVocationDate;
      this.approvedVocationDate = approvedVocationDate;
      this.currentSalary = currentSalary;
      this.proposedSalary = proposedSalary;
      this.approvedSalary = approvedSalary;
      this.comment = comment;
      this.approveComment = approveComment;
      this.currentVocationDate = currentVocationDate;
   }

}